### ISSUE TITLE
setwd("/ExampleProject/Data/GatherSource")

### ISSUE THREAD

**Issue by edusantana** [christophergandrud/Rep-Res-Book#74]
At chapter 4:
```latex
\paragraph{{\tt{setwd}}}\index{R function!setwd}

The {\tt{setwd}} command sets the current working directory (...) like this:

<<Ch4SetWorkingDir, eval=FALSE, echo=TRUE>>=
setwd("/ExampleProject/Data/GatherSource")
@
```

When I was reading this, I was thinking: Isn't the `Data` directory inside `Analysis`? What is this `GatherSource` directory for? When should we use it?

**Comment by christophergandrud** [comment]
Thanks for spotting this. (`GatherSource` was a directory in the 1st edition. It should now be `Analysis`). I've fixed it in f1c9a6f8723f197258371ca017b3535d02e9154f.

**Comment by jekimmel** [comment]
Christopher:

I still get copies of this email. Can I be deleted?

Thanks,
John

**Comment by christophergandrud** [comment]
Hi John

Sure, though I can't do it. It has to be done with your log it. Here are
the instructions:
https://help.github.com/articles/managing-notification-delivery-methods/

Just let me know if there are any issues.

Best
Christopher
